# -*- coding: us-ascii -*-

import sys

### Usage ###

#3-Indel_validation.py - Extract information from temp_part1.txt generated by 2-Indel_validation.py program

#input file: temp_part1.txt 

#By Julien Boutte, April 2019
#Copyright (c) 2019 Julien Boutte.
#Version 1.0.0

#This program is free software: you can redistribute it and/or modify it under
#the terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version. A copy of this license is available at <http://www.gnu.org/licenses/>.
#Great effort has been taken to make this software perform its said
#task, however, this software comes with ABSOLUTELY NO WARRANTY,
#not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

def mean(liste):
    total=0
    for i in liste:
        total=total+float(i)
    return (float(float(total)/len(liste)))

inputfile=open(sys.argv[1],'r')

output=open('temp_part2.txt','w')

pb=0

for line in inputfile:
    if line[0]!='>':
        temp=line.replace('\n','').split('\t')
        if len(temp)==7:
            output.write(temp[0]+'\t')
            if temp[3]=='[]':
                output.write('GAP'+'\t')
                output.write('NA'+'\t'+'NA'+'\t'+'NA'+'\t')
            else:
                output.write('No-GAP'+'\t')
                depth=temp[3].replace('[','')
                depth=depth.replace(']','')
                depth=depth.replace("'",'')
                depth=depth.split(',')
                liste_depth=[]
                for i in depth:
                    liste_depth.append(int(i))
                output.write(str(min(liste_depth))+'\t'+str(max(liste_depth))+'\t'+str(mean(liste_depth))+'\t')
            ###
            if temp[6]=='['']' or temp[6]=='[]':
                output.write(str('NA')+'\t'+str('NA')+'\t'+str('NA')+'\n')
                pb=pb+1
                #print line
                #print temporaire
            else:
                depth=temp[6].replace('[','')
                depth=depth.replace(']','')
                depth=depth.replace("'",'')
                depth=depth.split(',')
                liste_depth=[]
                for i in depth:
                    #print i
                    if 'NA' not in i:
                        liste_depth.append(int(i))
                output.write(str(min(liste_depth))+'\t'+str(max(liste_depth))+'\t'+str(mean(liste_depth))+'\n')
        else:
            print 'error'
            print line
            print 'program exit'
            exit()
        ###
    else:
        output.write(line)

output.close()           

print "Number of insertion/deletion per sample for which not information were available:",pb
print "a low number of this value is not a serious problem (example generated 1)"

